source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-remote-theme"

# Required plugins for just-the-docs
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-include-cache"
